### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by dtemps123** [sarafs1926/tprocv2_demos#2]
qick_tprocv2_experiments_mux/round_robin_benchmark.py

General code housekeeping tips
- Replace import statement for `expt_config` to import the methods/classes by name, this helps users track where things are defined.

qick_tprocv2_experiments_mux/section_008_save_data_to_h5.py
- Line 14: move `import os` to the preamble, every time you call this method, it will try to import os
- Line 15: I think theres an `isdir` method that we might want to use instead for confirming directory doesn't exist
- Line 19: I suggest `os.path.join` instead of string addition for the slashes (more robust on different OS)
- Line 31: suggest moving this method definition outside of the outer-level method and passing `group` as an argument (see: scope creep")
- Lines 34-35: unneeded line break
- Your in-video comments about passing the arguments with a default value of `None` and then later checking if they are/are not - thats how I usually do it. I don't think overloading the __init__ function will clarify things
-

**Comment by OliviaSeidel** [comment]
Changes made:
- Imported exit_cfg specifically, we don't need anything else from that file so this makes sense to do
- Moved import os in save class
-  os.path.isdir() specifically checks if a path is a directory or not, so I kept os.path.exists() to make sure I dont get an error if it doesn't exist 
- Changed all directory making lines in all classes to use os.path.join(), as this issue repeated throughout other classes as well
- Moved definition in def save_to_h5() to outside to avoid scope creep
- Removed line break
